name: generic_blocs
description: A new Flutter package project.
version: 0.0.1
author: Marcos Theophilo Gobbi Adamczuk
homepage: https://github.com/MacPardo/generic_blocs

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter_bloc: ^3.2.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

